version: '3.1'
services:
  odoo:
    image: odoo:15.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
    env_file:
      - odoo.env

  db:
    image: postgres:alpine
    env_file:
      - db.env